# Generated by Django 4.2 on 2026-05-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, choices=[('Dr', 'Docteur'), ('Pr', 'Professeur'), ('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], max_length=10, null=True, verbose_name='Titre')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('bio', models.TextField(blank=True, help_text="Parcours, domaines d'expertise, etc.", null=True, verbose_name='Biographie professionnelle')),
                ('bureau', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bureau/Local')),
                ('heures_consultation', models.TextField(blank=True, help_text='Ex: Lundi 14h-16h, Mercredi 10h-12h', null=True, verbose_name='Heures de consultation')),
                ('phone_pro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone professionnel')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/%Y/%m/', verbose_name='Photo de profil')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil enseignant',
                'verbose_name_plural': 'Profils enseignants',
                'db_table': 'teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stats', 'Statistiques générales'), ('chart_performance', 'Graphique de performance'), ('chart_completion', 'Taux de complétion'), ('chart_scores', 'Distribution des notes'), ('recent_activity', 'Activité récente'), ('top_students', 'Meilleurs étudiants'), ('struggling_students', 'Étudiants en difficulté'), ('upcoming_quizzes', 'Quiz à venir')], max_length=50, verbose_name='Type de widget')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Widget du tableau de bord',
                'verbose_name_plural': 'Widgets du tableau de bord',
                'ordering': ['teacher', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('quiz_completed', 'Quiz complété par un étudiant'), ('low_score', 'Score faible (< 50%)'), ('high_score', 'Score excellent (> 90%)'), ('new_question', 'Nouvelle question posée'), ('daily_summary', 'Résumé quotidien'), ('weekly_report', 'Rapport hebdomadaire')], max_length=50, verbose_name='Type de notification')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('send_email', models.BooleanField(default=True, verbose_name='Envoyer par email')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Envoyer par SMS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['user'], name='teacher_pro_user_id_ffcba3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['specialite'], name='teacher_pro_special_f454cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherdashboardwidget',
            unique_together={('teacher', 'widget_type')},
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('teacher', 'notification_type')},
        ),
    ]
