# Generated by Django 4.2 on 2026-02-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_level', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=50, null=True, verbose_name='Niveau titre')),
                ('heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='Titre')),
                ('is_qe', models.BooleanField(blank=True, default=False, null=True, verbose_name="Etre question d'examen")),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenu')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='Explication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Légende')),
                ('table', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prise de note en salle',
            },
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('docx', 'Word Document'), ('pptx', 'PowerPoint'), ('pdf', 'PDF')], max_length=50)),
                ('file', models.FileField(upload_to='lessons/uploads/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page_count', models.IntegerField(blank=True, default=0, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Document importé',
                'verbose_name_plural': 'Documents importés',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('mis_a_jour', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Résumé',
                'verbose_name_plural': 'Résumés',
            },
        ),
        migrations.CreateModel(
            name='ResumeIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('mis_a_jour', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Résumé par intelligence artificielle',
                'verbose_name_plural': 'Résumés par intelligence artificielle',
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Session d'étude",
                'verbose_name_plural': "Sessions d'étude",
            },
        ),
        migrations.CreateModel(
            name='UserAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_text', models.TextField(blank=True, null=True)),
                ('user_note', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessoncopy.copy')),
            ],
            options={
                'verbose_name': 'Annotation utilisateur',
                'verbose_name_plural': 'Annotations utilisateur',
            },
        ),
    ]
