# Generated by Django 4.2 on 2026-02-11 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecon', '0001_initial'),
        ('lessoncopy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysession',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeia',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter', verbose_name='Chapitre'),
        ),
        migrations.AddField(
            model_name='resume',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter', verbose_name='Chapitre'),
        ),
        migrations.AddField(
            model_name='resume',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='importer',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='copy',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddIndex(
            model_name='userannotation',
            index=models.Index(fields=['user', '-created_at'], name='lessoncopy__user_id_428570_idx'),
        ),
        migrations.AddIndex(
            model_name='userannotation',
            index=models.Index(fields=['copy', 'user'], name='lessoncopy__copy_id_94c883_idx'),
        ),
        migrations.AddIndex(
            model_name='userannotation',
            index=models.Index(fields=['user', 'copy'], name='lessoncopy__user_id_2e9976_idx'),
        ),
        migrations.AddIndex(
            model_name='userannotation',
            index=models.Index(fields=['updated_at'], name='lessoncopy__updated_907ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='userannotation',
            index=models.Index(fields=['copy', '-created_at'], name='lessoncopy__copy_id_8b0244_idx'),
        ),
        migrations.AddIndex(
            model_name='userannotation',
            index=models.Index(fields=['user', 'copy', 'color'], name='lessoncopy__user_id_2fb828_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'chapter', '-start_time'], name='lessoncopy__user_id_726b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['chapter', '-start_time'], name='lessoncopy__chapter_494e13_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', '-start_time'], name='lessoncopy__user_id_be5921_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['completed', 'user'], name='lessoncopy__complet_dd4149_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'completed', '-start_time'], name='lessoncopy__user_id_eec5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['duration_seconds'], name='lessoncopy__duratio_8c8e74_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'duration_seconds'], name='lessoncopy__user_id_ea02a7_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeia',
            index=models.Index(fields=['chapitre', '-date'], name='lessoncopy__chapitr_61477a_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeia',
            index=models.Index(fields=['-date'], name='lessoncopy__date_843765_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeia',
            index=models.Index(fields=['mis_a_jour'], name='lessoncopy__mis_a_j_de2e62_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeia',
            index=models.Index(fields=['chapitre', 'mis_a_jour'], name='lessoncopy__chapitr_242eff_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['createur', '-date'], name='lessoncopy__createu_c560d2_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['chapitre', '-date'], name='lessoncopy__chapitr_d571d9_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['createur', 'chapitre'], name='lessoncopy__createu_4172ba_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['mis_a_jour'], name='lessoncopy__mis_a_j_f52859_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['-date'], name='lessoncopy__date_a38496_idx'),
        ),
        migrations.AddIndex(
            model_name='importer',
            index=models.Index(fields=['-uploaded_at'], name='lessoncopy__uploade_4a45d5_idx'),
        ),
        migrations.AddIndex(
            model_name='importer',
            index=models.Index(fields=['processed', 'uploaded_at'], name='lessoncopy__process_06edc4_idx'),
        ),
        migrations.AddIndex(
            model_name='importer',
            index=models.Index(fields=['chapter', 'processed'], name='lessoncopy__chapter_a0e35c_idx'),
        ),
        migrations.AddIndex(
            model_name='importer',
            index=models.Index(fields=['file_type', 'chapter'], name='lessoncopy__file_ty_e84a34_idx'),
        ),
        migrations.AddIndex(
            model_name='importer',
            index=models.Index(fields=['processed'], name='lessoncopy__process_5d3132_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['chapter'], name='lessoncopy__chapter_e89bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['heading_level', 'chapter'], name='lessoncopy__heading_fb9639_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['is_qe', 'chapter'], name='lessoncopy__is_qe_a3663d_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['chapter', 'id'], name='lessoncopy__chapter_cdd6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['heading'], name='lessoncopy__heading_1ccc1a_idx'),
        ),
    ]
