# Generated by Django 4.2 on 2026-02-13 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessoncopy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='copy',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['created_at'], name='lessoncopy__created_918315_idx'),
        ),
    ]
