# Generated by Django 4.2 on 2026-02-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessoncopy', '0003_copy_created_at_copy_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='lessoncopy.importer'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='content',
            field=models.JSONField(blank=True, null=True, verbose_name='Contenu'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['importer', 'chapter'], name='lessoncopy__importe_911de3_idx'),
        ),
    ]
