# Generated by Django 4.2 on 2026-02-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prof', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du prof. ')),
                ('order', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('', 'Choisir niveau'), ('paces', 'PACES'), ('2ème année', '2ème année'), ('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('6ème année', '6ème année')], default='4ème année', max_length=50, verbose_name='Niveau')),
                ('semester', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=50, verbose_name='Semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Unité d'enseignement",
                'verbose_name_plural': "Unités d'enseignement",
            },
        ),
        migrations.CreateModel(
            name='UniteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapters', models.ManyToManyField(to='lecon.chapter')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.unite')),
            ],
            options={
                'verbose_name': "Section d'unité d'enseignement",
                'verbose_name_plural': "Sections d'unité d'enseignement",
            },
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['level', 'semester'], name='lecon_unite_level_767b87_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['title'], name='lecon_unite_title_8efa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['-created_at'], name='lecon_unite_created_d9e931_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['updated_at'], name='lecon_unite_updated_c3fd7b_idx'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['semester', 'level'], name='lecon_unite_semeste_9e8254_idx'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lecon.unite'),
        ),
        migrations.AddIndex(
            model_name='unitesection',
            index=models.Index(fields=['ue', 'title'], name='lecon_unite_ue_id_a84137_idx'),
        ),
        migrations.AddIndex(
            model_name='unitesection',
            index=models.Index(fields=['ue'], name='lecon_unite_ue_id_a2a851_idx'),
        ),
        migrations.AddIndex(
            model_name='unitesection',
            index=models.Index(fields=['-created_at'], name='lecon_unite_created_2a252d_idx'),
        ),
        migrations.AddIndex(
            model_name='unitesection',
            index=models.Index(fields=['updated_at'], name='lecon_unite_updated_a4883e_idx'),
        ),
        migrations.AddIndex(
            model_name='unitesection',
            index=models.Index(fields=['ue', '-created_at'], name='lecon_unite_ue_id_2f7266_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['ue', 'order'], name='lecon_chapt_ue_id_6d30f0_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_active', 'ue'], name='lecon_chapt_is_acti_723d51_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['ue', 'is_active', 'order'], name='lecon_chapt_ue_id_0f8f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['prof'], name='lecon_chapt_prof_fb75d5_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['updated_at'], name='lecon_chapt_updated_220919_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['-created_at'], name='lecon_chapt_created_ec2489_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['ue', '-created_at'], name='lecon_chapt_ue_id_0a1823_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('ue', 'order')},
        ),
    ]
