# Generated by Django 4.2 on 2026-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
