# Generated by Django 4.2 on 2026-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecon', '0002_alter_chapter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='level',
            field=models.CharField(choices=[('', 'Choisir niveau'), ('paces', 'PACES'), ('2ème année', '2ème année'), ('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('6ème année', '6ème année'), ('Prépa IQ', 'Prépa IQ'), ('Autre', 'Autre')], default='4ème année', max_length=50, verbose_name='Niveau'),
        ),
    ]
