# Generated by Django 4.2 on 2026-05-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecon', '0003_alter_unite_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='main_teacher',
            field=models.ForeignKey(blank=True, help_text='Enseignant titulaire ou responsable principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_teaching_unites', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant principal'),
        ),
        migrations.AddField(
            model_name='unite',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Sélectionnez les enseignants qui peuvent gérer cette unité', related_name='teaching_unites', to=settings.AUTH_USER_MODEL, verbose_name='Enseignants (titulaire et assistants)'),
        ),
        migrations.AddIndex(
            model_name='unite',
            index=models.Index(fields=['main_teacher'], name='lecon_unite_main_te_bcdad4_idx'),
        ),
    ]
