# Generated by Django 4.2 on 2026-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Est un enseignant'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_teacher'], name='users_is_teac_9776fc_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_teacher', 'is_active'], name='users_is_teac_be58ce_idx'),
        ),
    ]
