# Generated by Django 4.2 on 2026-02-11 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('mcq_features', models.PositiveIntegerField(default=0, help_text='Nombre maximum de QCM autorisé')),
                ('mcq_exam_feature', models.PositiveIntegerField(default=0, help_text='Nombre maximum de EXAMEN DE QCM autorisé')),
                ('qa_features', models.PositiveIntegerField(default=0, help_text='Nombre maximum de QUESTION ET REPONSE autorisé')),
                ('qa_exam_feature', models.PositiveIntegerField(default=0, help_text='Nombre maximum de EXAMEN DE QUESTION ET REPONSE autorisé')),
                ('tf_features', models.PositiveIntegerField(default=0, help_text='Nombre maximum de VRAIE OU FAUSSE question autorisé')),
                ('validity_day_number', models.PositiveIntegerField(help_text='Number of days the subscription is valid')),
                ('can_add_resume', models.BooleanField(default=False)),
                ('can_add_notes', models.BooleanField(default=False)),
                ('can_view_terminology', models.BooleanField(default=False)),
                ('can_practice_terminology', models.BooleanField(default=False)),
                ('can_view_public_flashcard', models.BooleanField(default=False)),
                ('can_practice_quizlet_learning_mode', models.BooleanField(default=False)),
                ('can_view_image_quiz', models.BooleanField(default=False)),
                ('can_practice_image_quiz', models.BooleanField(default=False)),
                ('can_ask_question', models.BooleanField(default=False)),
                ('can_view_dicussion', models.BooleanField(default=False)),
                ('can_add_own_terminology', models.BooleanField(default=False)),
                ('can_add_own_flashcard', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_with', models.CharField(choices=[('mvola', 'MVola'), ('orange', 'Orange Money'), ('airtel', 'Airtel Money'), ('cash', 'Payment direct')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('phone_number_of_payment', models.CharField(blank=True, help_text='Ex: 0341234567 (sans +261 ni espaces)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Numéro malgache requis (ex: 0341234567)', regex='^03[2-8]\\d{7}$')])),
                ('reference_of_payment', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('payement_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Vérifié'), ('rejected', 'Refusé')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planning_date_to_start', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('mcq_attempts_used', models.PositiveIntegerField(default=0)),
                ('mcq_exam_attempts_used', models.PositiveIntegerField(default=0)),
                ('qa_attempts_used', models.PositiveIntegerField(default=0)),
                ('qa_exam_attempts_used', models.PositiveIntegerField(default=0)),
                ('tf_attempts_used', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('payement_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('expired', 'Expiré'), ('active', 'Actif')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('payment_created', 'Payment Created'), ('payment_reviewed', 'Payment Reviewed'), ('subscription_created', 'Subscription Created'), ('subscription_reviewed', 'Subscription Reviewed'), ('quiz_start', 'Quiz Started'), ('quiz_complete', 'Quiz Completed'), ('exam_start', 'Exam Started'), ('exam_complete', 'Exam Completed'), ('feature_access', 'Feature Accessed'), ('subscription_start', 'Subscription Started'), ('subscription_end', 'Subscription Ended')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Usage Audit',
                'verbose_name_plural': 'Usage Audits',
                'ordering': ['-action_at'],
            },
        ),
    ]
