# Generated by Django 4.2 on 2026-02-11 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('student', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['code'], name='subscriptio_code_80ee95_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['price'], name='subscriptio_price_9ccd9f_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['validity_day_number'], name='subscriptio_validit_afe894_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusageaudit',
            index=models.Index(fields=['subscription', 'action_type'], name='subscriptio_subscri_80614e_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusageaudit',
            index=models.Index(fields=['action_at'], name='subscriptio_action__4b6b03_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionusageaudit',
            index=models.Index(fields=['student'], name='subscriptio_student_02b127_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['payement_status'], name='subscriptio_payemen_b53bca_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['created_at'], name='subscriptio_created_09827c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['student', 'payement_status'], name='subscriptio_student_c4f144_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['student', 'feature'], name='subscriptio_student_20f57b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['expires_at'], name='subscriptio_expires_53ce37_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['approved_by'], name='subscriptio_approve_db5b26_idx'),
        ),
    ]
