# Generated by Django 4.2 on 2026-02-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('paces', 'PACES'), ('2ème année', '2ème année'), ('3ème année', '3ème année'), ('4ème année', '4ème année'), ('5ème année', '5ème année'), ('6ème année', '6ème année'), ('interne', 'Interne')], db_index=True, max_length=20, null=True, verbose_name="Niveau d'études")),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Établissement')),
                ('student_id_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro IM')),
                ('is_active_student', models.BooleanField(default=True, verbose_name='Étudiant actif')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('preferred_learning_style', models.CharField(blank=True, choices=[('visual', 'Visuel'), ('auditory', 'Auditif'), ('kinesthetic', 'Kinesthésique'), ('reading', 'Lecture/Écriture')], max_length=50, null=True, verbose_name="Style d'apprentissage préféré")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'verbose_name_plural': 'Profils Étudiants',
                'ordering': ['-created_at'],
            },
        ),
    ]
