# Generated by Django 4.2 on 2026-02-11 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecon', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='truefalseresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='truefalsequiz',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='truefalsequiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quizzes.qaattempt'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questionanswer'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaresult',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='qaresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='qaquiz',
            name='chapters',
            field=models.ManyToManyField(to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='qaquiz',
            name='questions',
            field=models.ManyToManyField(to='quizzes.questionanswer'),
        ),
        migrations.AddField(
            model_name='qaquiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_quizzes', to='lecon.unite'),
        ),
        migrations.AddField(
            model_name='qaattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.qaquiz'),
        ),
        migrations.AddField(
            model_name='qaattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaanswer',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='qaanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questionanswer', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='qaanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='mcqresult',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='mcqresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='chapters',
            field=models.ManyToManyField(to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='questions',
            field=models.ManyToManyField(to='quizzes.mcq'),
        ),
        migrations.AddField(
            model_name='mcqquiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_quizzes', to='lecon.unite'),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.mcqquiz'),
        ),
        migrations.AddField(
            model_name='mcqattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcq',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecon.chapter'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='truefalseresult',
            index=models.Index(fields=['student', 'chapter', '-created_at'], name='quizzes_tru_student_32651c_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalseresult',
            index=models.Index(fields=['chapter', '-score'], name='quizzes_tru_chapter_ed4405_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalseresult',
            index=models.Index(fields=['student', '-score'], name='quizzes_tru_student_b219de_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalseresult',
            index=models.Index(fields=['score'], name='quizzes_tru_score_38b536_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalseresult',
            index=models.Index(fields=['-created_at'], name='quizzes_tru_created_dac360_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalseresult',
            index=models.Index(fields=['student', 'chapter', 'score'], name='quizzes_tru_student_8cee2d_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalsequiz',
            index=models.Index(fields=['chapter', '-created_at'], name='quizzes_tru_chapter_e814ab_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalsequiz',
            index=models.Index(fields=['created_by', '-created_at'], name='quizzes_tru_created_e9d69b_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalsequiz',
            index=models.Index(fields=['updated_at'], name='quizzes_tru_updated_5b9331_idx'),
        ),
        migrations.AddIndex(
            model_name='truefalsequiz',
            index=models.Index(fields=['chapter', 'answer'], name='quizzes_tru_chapter_5d4c91_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['similarity_score'], name='quizzes_stu_similar_cfcfa3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['teacher_mark'], name='quizzes_stu_teacher_cc29f6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', '-id'], name='quizzes_stu_attempt_1d2287_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['chapter', '-created_at'], name='quizzes_que_chapter_872bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['created_by', '-created_at'], name='quizzes_que_created_7f683a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['updated_at'], name='quizzes_que_updated_0ee761_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['-created_at'], name='quizzes_que_created_f3622e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionanswer',
            index=models.Index(fields=['chapter', 'created_by', '-created_at'], name='quizzes_que_chapter_248403_idx'),
        ),
        migrations.AddIndex(
            model_name='qaresult',
            index=models.Index(fields=['student', 'chapter', '-created_at'], name='quizzes_qar_student_60405a_idx'),
        ),
        migrations.AddIndex(
            model_name='qaresult',
            index=models.Index(fields=['chapter', '-score'], name='quizzes_qar_chapter_06b689_idx'),
        ),
        migrations.AddIndex(
            model_name='qaresult',
            index=models.Index(fields=['student', '-score'], name='quizzes_qar_student_08cf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='qaresult',
            index=models.Index(fields=['score'], name='quizzes_qar_score_853365_idx'),
        ),
        migrations.AddIndex(
            model_name='qaresult',
            index=models.Index(fields=['-created_at'], name='quizzes_qar_created_6f40af_idx'),
        ),
        migrations.AddIndex(
            model_name='qaresult',
            index=models.Index(fields=['student', 'chapter', 'score'], name='quizzes_qar_student_320dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['subject', '-created_at'], name='quizzes_qaq_subject_035f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['-start_date'], name='quizzes_qaq_start_d_16e775_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['end_date'], name='quizzes_qaq_end_dat_0f0d14_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['subject', 'start_date', 'end_date'], name='quizzes_qaq_subject_9cad71_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['updated_at'], name='quizzes_qaq_updated_6604a8_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['subject', 'title'], name='quizzes_qaq_subject_05a1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='qaquiz',
            index=models.Index(fields=['score_to_pass'], name='quizzes_qaq_score_t_4e8401_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['student', '-start_time'], name='quizzes_qaa_student_a7084b_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['quiz', '-start_time'], name='quizzes_qaa_quiz_id_7869ad_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['student', 'quiz', '-start_time'], name='quizzes_qaa_student_ac063f_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['completed', 'student'], name='quizzes_qaa_complet_b5d12f_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['score'], name='quizzes_qaa_score_71265b_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['teacher_score'], name='quizzes_qaa_teacher_8d91ca_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['similarity_score'], name='quizzes_qaa_similar_85fb7b_idx'),
        ),
        migrations.AddIndex(
            model_name='qaattempt',
            index=models.Index(fields=['student', 'completed', '-start_time'], name='quizzes_qaa_student_4e6dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='qaanswer',
            index=models.Index(fields=['student', '-created_at'], name='quizzes_qaa_student_851d51_idx'),
        ),
        migrations.AddIndex(
            model_name='qaanswer',
            index=models.Index(fields=['chapter', 'student', '-created_at'], name='quizzes_qaa_chapter_6e58f7_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['user', 'chapter', '-created_at'], name='quizzes_mcq_user_id_9b089f_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['chapter', '-score'], name='quizzes_mcq_chapter_512349_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['user', '-score'], name='quizzes_mcq_user_id_6d9888_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['score'], name='quizzes_mcq_score_a4882c_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['user', 'chapter', 'score'], name='quizzes_mcq_user_id_c416bc_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['-created_at'], name='quizzes_mcq_created_b39735_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['subject', '-created_at'], name='quizzes_mcq_subject_3b67f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['-start_date'], name='quizzes_mcq_start_d_aa13c4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['end_date'], name='quizzes_mcq_end_dat_957ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['subject', 'start_date', 'end_date'], name='quizzes_mcq_subject_c55f37_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['updated_at'], name='quizzes_mcq_updated_8ddcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['subject', 'title'], name='quizzes_mcq_subject_01d3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqquiz',
            index=models.Index(fields=['score_to_pass'], name='quizzes_mcq_score_t_230a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['student', '-start_time'], name='quizzes_mcq_student_2f2b11_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['quiz', '-start_time'], name='quizzes_mcq_quiz_id_97d3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['student', 'quiz', '-start_time'], name='quizzes_mcq_student_1c9f07_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['completed', 'student'], name='quizzes_mcq_complet_aa1de6_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['score'], name='quizzes_mcq_score_2e213f_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['student', 'score'], name='quizzes_mcq_student_4669ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqattempt',
            index=models.Index(fields=['quiz', 'score'], name='quizzes_mcq_quiz_id_6ced80_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['chapter', '-created_at'], name='quizzes_mcq_chapter_c78da9_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['created_by', '-created_at'], name='quizzes_mcq_created_092613_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['chapter', 'created_by'], name='quizzes_mcq_chapter_ef823e_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['updated_at'], name='quizzes_mcq_updated_9dd319_idx'),
        ),
        migrations.AddIndex(
            model_name='mcq',
            index=models.Index(fields=['-created_at'], name='quizzes_mcq_created_9a9907_idx'),
        ),
    ]
