# Generated by Django 4.2 on 2026-03-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truefalsequiz',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
