# Generated by Django 4.2 on 2026-05-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_truefalsequiz_time_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqresult',
            options={'ordering': ['-created_at', 'student']},
        ),
        migrations.RemoveIndex(
            model_name='mcqresult',
            name='quizzes_mcq_user_id_9b089f_idx',
        ),
        migrations.RemoveIndex(
            model_name='mcqresult',
            name='quizzes_mcq_user_id_6d9888_idx',
        ),
        migrations.RemoveIndex(
            model_name='mcqresult',
            name='quizzes_mcq_user_id_c416bc_idx',
        ),
        migrations.RenameField(
            model_name='mcqresult',
            old_name='user',
            new_name='student',
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['student', 'chapter', '-created_at'], name='quizzes_mcq_student_bbaf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['student', '-score'], name='quizzes_mcq_student_f41c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqresult',
            index=models.Index(fields=['student', 'chapter', 'score'], name='quizzes_mcq_student_289d70_idx'),
        ),
    ]
